# https://circleci.com/docs/2.1/language-javascript/
version: 2.1
commands:
  extract-changelog-version:
    steps:
      - run:
          name: extract changelog version
          working_directory: ~/assign-reducers
          command: |
            VERSION=$(head -n1 CHANGELOG.md | grep -o '\([0-9]\+\.\)\{2\}[0-9]\+')
            echo "export VERSION=${VERSION}" >> $BASH_ENV
            echo "export CHANGELOG_VERSION=${VERSION}" >> $BASH_ENV
            echo "changelog version: ${VERSION}"

  extract-package-json-version:
    steps:
      - run:
          name: extract package.json version
          working_directory: ~/assign-reducers
          command: |
            PACKAGE_JSON_VERSION=$(node -e "console.info(require('./package').version)")
            echo "export PACKAGE_JSON_VERSION=${PACKAGE_JSON_VERSION}" >> $BASH_ENV
            echo "package.json version: ${PACKAGE_JSON_VERSION}"

  extract-published-version:
    steps:
      - run:
          name: extract latest published version
          working_directory: ~/assign-reducers
          command: |
            LIVE_VERSION=$(npm show @haensl/assign-reducers version || true)
            [ -z "${LIVE_VERSION}" ] && LIVE_VERSION='0.0.0'
            echo "export LIVE_VERSION=${LIVE_VERSION}" >> ${BASH_ENV}
            echo "latest published version: ${LIVE_VERSION}"

  extract-versions:
    steps:
      - extract-changelog-version
      - extract-package-json-version
      - extract-published-version

  init:
    steps:
      - run:
          name: update npm
          command: sudo npm install -g npm@latest

  prepare-repo:
    steps:
      - checkout
      - restore_cache:
          keys: assign-reducers-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: assign-reducers-dependencies-{{ checksum "package-lock.json" }}
      - extract-versions

  create-npm-project:
    parameters:
      project_name:
        description: project name
        type: string
        default: test-app
    steps:
      - run:
          name: create npm application
          command: |
            cd /tmp
            mkdir << parameters.project_name >>
            cd << parameters.project_name >> && npm init -y

  create-react-app:
    parameters:
      project_name:
        description: project name
        type: string
        default: test-app
    steps:
      - run:
          name: create react applicatiion
          command: |
            cd /tmp
            npx --quiet create-react-app << parameters.project_name >> --use-npm

  package-information:
    steps:
      - run:
          name: install tree
          command: sudo apt-get -y install tree
      - run:
          name: gather bundle information
          command: |
            npm info @haensl/assign-reducers@${VERSION} > ./bundle.info
            tree -s node_modules/@haensl/assign-reducers >> ./bundle.info
      - store_artifacts:
          path: bundle.info

workflows:
  version: 2
  default:
    when: always
    jobs:
      - lint
      - test
      - bundle:
          requires:
            - lint
            - test
      - bundle-test-esm-js:
          requires:
            - bundle
      - bundle-test-cjs-js:
          requires:
            - bundle
      - ensure-versioned-correctly:
          requires:
            - bundle
      - publish:
          requires:
            - ensure-versioned-correctly
            - bundle-test-esm-js
            - bundle-test-cjs-js
          filters:
            branches:
              only: master
      - package-test-esm-js:
          requires:
            - publish
      - package-test-cjs-js:
          requires:
            - publish
      - publish-github-release:
          requires:
            - package-test-esm-js
            - package-test-cjs-js

jobs:
  lint:
    docker:
      - image: circleci/node:lts
    working_directory: ~/assign-reducers
    steps:
      - init
      - prepare-repo
      - run:
          name: create test-results-folder
          command: mkdir -p test-results/eslint
      - run:
          name: lint
          command: npm run lint:ci
      - store_test_results:
          path: test-results

  test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/assign-reducers
    steps:
      - init
      - prepare-repo
      - run:
          name: unit tests
          command: npm run test:ci
      - store_test_results:
          path: test-results

  bundle:
    docker:
      - image: circleci/node:lts
    working_directory: ~/assign-reducers
    steps:
      - init
      - prepare-repo
      - extract-versions
      - run:
          name: generate production bundle
          command: npm run build
      - store_artifacts:
          path: dist
      - run:
          name: pack
          environment:
            NODE_ENV: 'production'
          command: |
            npm pack
            mv haensl-assign-reducers-${VERSION}.tgz haensl-assign-reducers.tgz
      - store_artifacts:
          path: haensl-assign-reducers.tgz
      - persist_to_workspace:
          root: ./
          paths:
            - dist
            - __package-tests__
            - CHANGELOG.md
            - README.md
            - LICENSE
            - package.json
            - package-lock.json
            - index.js
            - .npmignore
            - haensl-assign-reducers.tgz

  bundle-test-cjs-js:
    docker:
      - image: circleci/node:lts
    steps:
      - init
      - attach_workspace:
          at: ~/assign-reducers
      - extract-versions
      - create-npm-project
      - run:
          name: copy cjs package test
          working_directory: /tmp/test-app
          command: |
            cp ~/assign-reducers/__package-tests__/cjs.package.test.js ./
      - run:
          name: install module
          working_directory: /tmp/test-app
          command: |
            npm i ~/assign-reducers/haensl-assign-reducers.tgz
      - run:
          name: install dependencies
          working_directory: /tmp/test-app
          command: |
            npm i jest redux
      - run:
          name: test cjs.js module
          working_directory: /tmp/test-app
          command: |
            node_modules/.bin/jest

  bundle-test-esm-js:
    docker:
      - image: circleci/node:lts
    steps:
      - init
      - attach_workspace:
          at: ~/assign-reducers
      - extract-versions
      - create-react-app
      - run:
          name: copy esm package test
          working_directory: /tmp/test-app
          command: |
            cp ~/assign-reducers/__package-tests__/esm.package.test.js ./src
      - run:
          name: install dependencies
          working_directory: /tmp/test-app
          command: |
            npm i redux
      - run:
          name: install module
          working_directory: /tmp/test-app
          command: |
            npm i -S ~/assign-reducers/haensl-assign-reducers.tgz
      - run:
          name: test esm.js module
          working_directory: /tmp/test-app
          command: |
            npm test

  ensure-versioned-correctly:
    docker:
      - image: circleci/node:lts
    working_directory: ~/assign-reducers
    steps:
      - init
      - attach_workspace:
          at: ~/assign-reducers
      - extract-versions
      - run:
          name: changelog matches package.json
          command: |
            test ${PACKAGE_JSON_VERSION} = ${CHANGELOG_VERSION}
      - run:
          name: pacakge.json greater than live
          command: |
            node \<<VERSION_CHECK
            const pkgVersion = require('./package').version
              .split('.')
              .map((i) => parseInt(i, 10));
            const liveVersion = process.env.LIVE_VERSION
              .split('.')
              .map((i) => parseInt(i, 10));
            const isGreater = pkgVersion.reduce((isGreater, part, i) => {
              return isGreater || (part > liveVersion[i]);
            }, false);
            if (!isGreater) {
              process.exit(1);
            }
            VERSION_CHECK

  publish:
    docker:
      - image: circleci/node:lts
    working_directory: ~/assign-reducers
    steps:
      - init
      - attach_workspace:
          at: ~/assign-reducers
      - run:
          name: setup npm registry token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: publish node module
          command: npm publish --access public

  package-test-esm-js:
    docker:
      - image: circleci/node:lts
    steps:
      - init
      - attach_workspace:
          at: ~/assign-reducers
      - create-react-app
      - run:
          name: install module
          working_directory: /tmp/test-app
          command: |
            npm i -S @haensl/assign-reducers
      - run:
          name: install dependencies
          working_directory: /tmp/test-app
          command: |
            npm i redux
      - run:
          name: copy esm package test
          working_directory: /tmp/test-app
          command: |
            cp ~/assign-reducers/__package-tests__/esm.package.test.js ./src
      - run:
          name: test esm.js module
          working_directory: /tmp/test-app
          command: |
            npm test
      - package-information

  package-test-cjs-js:
    docker:
      - image: circleci/node:lts
    steps:
      - init
      - attach_workspace:
          at: ~/assign-reducers
      - extract-versions
      - create-npm-project
      - run:
          name: copy cjs package test
          working_directory: /tmp/test-app
          command: |
            cp ~/assign-reducers/__package-tests__/cjs.package.test.js ./
      - run:
          name: install module
          working_directory: /tmp/test-app
          command: |
            npm i @haensl/assign-reducers
      - run:
          name: install dependencies
          working_directory: /tmp/test-app
          command: |
            npm i redux jest
      - run:
          name: test cjs.js module
          working_directory: /tmp/test-app
          command: |
            node_modules/.bin/jest

  publish-github-release:
    docker:
      - image: cibuilds/github
    steps:
      - attach_workspace:
          at: ~/assign-reducers
      - extract-changelog-version
      - run:
          name: publish github release
          working_directory: ~/assign-reducers
          command: |
            cp ./haensl-assign-reducers.tgz ./haensl-assign-reducers-${VERSION}.tgz
            CHANGES=$(awk "/## ${VERSION}/,/^$/" CHANGELOG.md)
            echo "Publishing release v${VERSION} to Github.\nChanges:"
            echo $CHANGES
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete -n "v${VERSION}" -b "${CHANGES}" "v${VERSION}" ./haensl-assign-reducers-${VERSION}.tgz
